### ISSUE TITLE
Gestionar correctament els reply a comentaris privats

### ISSUE THREAD

**Issue by jaumemoral** [jaumemoral/mailtoticket#18]
La idea seria crear un comentari privat, pero per aixo hem de poder discriminar directament amb el comentari, si es una notificació d'un comentari privat o public. Ho hem demanat a upcnet perque es pugui afegir a la plantilla del mail.

**Comment by alexm** [comment]
En alguns sistemes de tiquets s'utilitza una adreça de correu diferent per
als comentaris privats, per exemple: help-private@example.com.
El dia 14/04/2015 4:34 p. m., "Jaume Moral" <notifications@github.com> va
escriure:

**Comment by jaumemoral** [comment]
Desde GN6 han acceptat la nostra millora, aixi que aviat podrem marcar les notificacions de missatges privats amb un PRIVAT al subject i per tant al fer reply sabrem que hem de creat un comentari privat.

**Comment by jaumemoral** [comment]
@alexm , sobre el que comentes... doncs ara mateix es podria arribar fent que els mails que arribin a l'adreça que comenten tinguin un paràmetre addicional que seria comentariPrivat=S, igual que els de webmaster poden anar amb l'equip resolutor ja assignat. L'unic es que aixo només aplica a la creacio de tickets, no al posar comentaris, pero es podria ampliar facilment.

**Comment by jaumemoral** [comment]
Ja se'ns informa desde GN6 si el mail de notificació es d'un comentari privat o no. Hem posat una nova regex per poder trobar aquesta informació al subject i sembla que va bé... pero encara que creem el comentari com COMENT_TIQUET_PRIVAT es crea com a public igualment.

Obro ticket a gn6 a veure si ho poden validar

**Comment by jaumemoral** [comment]
Els comentaris es detecten correctament. El que falla es la creació. Confirmat.

https://eatic.upc.edu/atic/control/aticTiquetDetallDadesGenerals?requirementId=594901

**Comment by jaumemoral** [comment]
Fallo meu. Tot va correcte. Ara ja es poden fer replys a notificacions de comentaris privats i el comentari queda privat.
