### ISSUE TITLE
Problemes amb els mails que arriben de comptes generics

### ISSUE THREAD

**Issue by jaumemoral** [jaumemoral/mailtoticket#21]
A notes ho haviem solucionat posant una capçalera amb l'usuari connectat.

Aqui coses com ara fib.reserves.fib existeixen a identitat digital pero dona error a l'hora de crear el ticket. Com ho resolem? Posem per davant les adreces mapejades "manualment" a usuaris abans del resultat de identitat digital?

**Comment by aaguilera** [comment]
Entenc que l'error és que el webservice per identificar el remitent a partir de l'email no funciona amb adreces genèriques. És això?
En el cas de Camins, com a mínim, ens seria igual si aquest tipus de mails no fóssin processats per mailtoticket, perquè normalment aquestes busties només les fem servir per rebre mails, no per enviar-los. En canvi hi ha altres bústies genèriques, associades a persones, com "director.camins@upc.edu" o "secretari.academic.camins@upc.edu" en que sí seria interessant saber què passaria. Podries comprovar, per exemple, què retornaria el webservice per a aquestes adreces? (aquí en tens les persones "reals" a les què pertanyen, per si et serveix d'alguna cosa: http://www.camins.upc.edu/escola/estructura-i-organtizacio/organs-unipersonals/director-i-equip-directiu).

**Comment by jaumemoral** [comment]
T'ho miro. Fare un petit "main" que permeti utilitzar el servei d'identitat digital per fer la consulta dels mails que em dones.

Pel que he vist, els problemes els he tingut amb alias locals de mails generics i amb mails locals de notes que no tenen un usuari creat realment. Son casos estranys.

El que he fet per ara es posar les excepcions per davant del que torna identitat digital i tractar aquestes adreces com a excepcions.

**Comment by alexm** [comment]
Una altra possibilitat és que si falla la cerca de la identital digital, el
tiquet es creï amb un usuari genèric de la unitat enlloc d'avortar la
creació.

Nosaltres tenim un d'aquests usuaris per crear tiquets d'usuaris del DAC
que no són al directori. Segurament és un patró habitual en altres unitats.
El dia 01/07/2015 21:02, "Jaume Moral" <notifications@github.com> va
escriure:

**Comment by jaumemoral** [comment]
@alexm , la teva idea em sembla perillosa per culpa del SPAM. Si solucionem previament aquest problema, em semblaria perfecte. Només caldria afegir quin es l'usuari amb que volem crear els tickets "anonims"

@aaguilera , he provat els usuaris que m'has dit i no em donen la persona, sino l'usuari generic de LDAP corresponent al mail, es a dir, "director.camins" i "secretari.academic.camins". Els tickets es crearien amb aquest usuari, que no se si es bo o dolent, pero es aixi.

**Comment by alexm** [comment]
És cert que el tema de l'spam podria ser un problema. Si més no, es podria
aplicar la solució que proposava a un conjunt d'adreces o dominis que es
puguin personalitzar.

2015-07-02 16:13 GMT+02:00 Jaume Moral <notifications@github.com>:

**Comment by aaguilera** [comment]
El dia 2 de juliol de 2015, 16:13, Jaume Moral <notifications@github.com>
ha escrit:

> @aaguilera <https://github.com/aaguilera> , he provat els usuaris que
> m'has dit i no em donen la persona, sino l'usuari generic de LDAP
> corresponent al mail, es a dir, "director.camins" i
> "secretari.academic.camins". Els tickets es crearien amb aquest usuari, que
> no se si es bo o dolent, pero es aixi.
>

Bé, crec que això ja ens serviria. El que em preocupava era que donés error
el webservice.
