### ISSUE TITLE
Fer la part de buscar username a partir de mail amb un servei SOA

### ISSUE THREAD

**Issue by jaumemoral** [jaumemoral/mailtoticket#5]

**Comment by jaumemoral** [comment]
Ho he demanat a la OSI i la Iolanda s'ha posat en contacte amb mi per veure que necessito exactament, aixi que entenc que la cosa tira endavant.

**Comment by joangiralt** [comment]
Visca!!! Si la cosa no tira avisa!!!

**Comment by jaumemoral** [comment]
El webservice ja està en marxa a preproducció. Estem pendents de que estigui a producció per fer el canvi del cercador de persones basat en LDAP al cercador basat en SOA

**Comment by joangiralt** [comment]
Jaume, ho he rebut al correu personal. També contesto però potser millor si
és des de joan.giralt@upc.edu ;)

Fins ara!!!

Joan

El dia 9 de juny de 2015, 16:25, Jaume Moral <notifications@github.com> ha
escrit:

**Comment by jaumemoral** [comment]
Doncs jo també he rebut l'avís al personal. Suposo que el compte aquest de github el tenim vinculat a la nostra adreça personal. No se si per un projecte concret es pot canviar...

**Comment by joangiralt** [comment]
Ni idea, la veritat però bé... tampoc em cauran els anells. Si ho esbrines
m'ho dius ;)
Enhorabona que ja comenceu amb el projecte!!! :)))))

El dia 9 de juny de 2015, 16:43, Jaume Moral <notifications@github.com> ha
escrit:

**Comment by jaumemoral** [comment]
Ep, ja tenim el servei en producció. La última versió del codi ja incorpora els canvis per funcionar amb el nou servei GestioIdentitat  i ja no queda ni rastre dels scripts per consultar al LDAP.

Dono la incidència per tancada

**Comment by joangiralt** [comment]
m'has d'explicar millor això!

El dia 19 de juny de 2015, 15:27, Jaume Moral <notifications@github.com> ha
escrit:

**Comment by jaumemoral** [comment]
@joangiralt , el que he fet es consultar l'usuari a partir del mail utilitzant aquest servei que es va posar al bus SOA de producció la setmana passada.

https://bus-soa.upc.edu/GestioIdentitat/Personesv6?wsdl

Concretament utilitzo la operació "llistaPersones", que ara permet buscar per email, cosa que a la versio v5 no es permetia. Suposo que la documentació al Espai SOA encara està pendent, pero al WSDL ja està "autoexplicat".
