### ISSUE TITLE
Fer un filtre que reobri tickets tancats

### ISSUE THREAD

**Issue by jaumemoral** [jaumemoral/mailtoticket#6]
La idea es aplicarlo a una adreça interna, que no sigui el comportament per defecte de l'adreça pública

**Comment by alexm** [comment]
No sé si acabo d'entendre la història d'usuari. El que em trobo jo és que de vegades voldria que una resposta sobre un tiquet tancat el reobri però passat un temps raonable (1 mes, 1 any, etc.) preferiria que es creï un tiquet nou, encara que sigui del mateix tema.

No sé si això ho té en compte el mailtoticket actualment però crec que és una història d'usuari habitual.

**Comment by jaumemoral** [comment]
Trobo interessant el que dius. Actualment si detecta una resposta a un ticket tancat, no es fa cap tractament. Aixo es aixi perque moltes vegades la resposta un cop tancat es un simple "gràcies".

La meva idea inicial es el dispatcher tingui alguna forma de redirigir aquest mail a una adreça on hi hagi una altra instancia de mailtoticket configurada perque permeti comentaris a tickets tancats. Per tant, que sigui una decisio del dispatcher que fer amb aquest mail.

En fi... crec qeu abans de fer feina, millor tenir clar pros i contres de que implica reobrir tickets automaticament.

**Comment by jaumemoral** [comment]
Ja està fet. Si en comptes de posar el FiltreRepy es posa el FiltreRepyReobrint, reobre el ticket abans de posar el comentari.
